# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_coal_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_base_coal_dialog(object):
    def setupUi(self, base_coal_dialog):
        base_coal_dialog.setObjectName("base_coal_dialog")
        base_coal_dialog.resize(1200, 600)
        self.comboBox_3 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(base_coal_dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_7 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(100, 360, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.screening_btn = QtWidgets.QPushButton(base_coal_dialog)
        self.screening_btn.setGeometry(QtCore.QRect(30, 480, 170, 50))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.screening_btn.setFont(font)
        self.screening_btn.setObjectName("screening_btn")
        self.label_3 = QtWidgets.QLabel(base_coal_dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(base_coal_dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(base_coal_dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_5 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(100, 240, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(100, 420, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label = QtWidgets.QLabel(base_coal_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(base_coal_dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_6 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(100, 300, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 60, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(base_coal_dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(base_coal_dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox_4 = QtWidgets.QComboBox(base_coal_dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(100, 180, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.result_table = QtWidgets.QTableWidget(base_coal_dialog)
        self.result_table.setGeometry(QtCore.QRect(230, 60, 961, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_table.sizePolicy().hasHeightForWidth())
        self.result_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.result_table.setFont(font)
        self.result_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.result_table.setAlternatingRowColors(True)
        self.result_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(0)
        self.result_table.verticalHeader().setCascadingSectionResizes(False)
        self.label_num = QtWidgets.QLabel(base_coal_dialog)
        self.label_num.setGeometry(QtCore.QRect(230, 520, 151, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.label_num.setFont(font)
        self.label_num.setText("")
        self.label_num.setObjectName("label_num")

        self.retranslateUi(base_coal_dialog)
        self.screening_btn.clicked.connect(base_coal_dialog.screening_btn_click)
        QtCore.QMetaObject.connectSlotsByName(base_coal_dialog)

    def retranslateUi(self, base_coal_dialog):
        _translate = QtCore.QCoreApplication.translate
        base_coal_dialog.setWindowTitle(_translate("base_coal_dialog", "基础煤种指标库"))
        self.comboBox_3.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_3.setItemText(1, _translate("base_coal_dialog", "1985-1990"))
        self.comboBox_3.setItemText(2, _translate("base_coal_dialog", "1991-1995"))
        self.comboBox_3.setItemText(3, _translate("base_coal_dialog", "1996-1998"))
        self.comboBox_3.setItemText(4, _translate("base_coal_dialog", "1999-2002"))
        self.comboBox_3.setItemText(5, _translate("base_coal_dialog", "2003-2005"))
        self.comboBox_3.setItemText(6, _translate("base_coal_dialog", "2006-2010"))
        self.comboBox_3.setItemText(7, _translate("base_coal_dialog", "2011-2015"))
        self.comboBox_3.setItemText(8, _translate("base_coal_dialog", "2016至今"))
        self.label_5.setText(_translate("base_coal_dialog", "热强度"))
        self.comboBox_7.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_7.setItemText(1, _translate("base_coal_dialog", "特高"))
        self.comboBox_7.setItemText(2, _translate("base_coal_dialog", "高"))
        self.comboBox_7.setItemText(3, _translate("base_coal_dialog", "中"))
        self.comboBox_7.setItemText(4, _translate("base_coal_dialog", "低"))
        self.comboBox_7.setItemText(5, _translate("base_coal_dialog", "特低"))
        self.screening_btn.setText(_translate("base_coal_dialog", "筛选"))
        self.label_3.setText(_translate("base_coal_dialog", "煤种"))
        self.label_8.setText(_translate("base_coal_dialog", "灰分"))
        self.label_7.setText(_translate("base_coal_dialog", "硬度"))
        self.comboBox_5.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_5.setItemText(1, _translate("base_coal_dialog", "A级"))
        self.comboBox_5.setItemText(2, _translate("base_coal_dialog", "B级"))
        self.comboBox_5.setItemText(3, _translate("base_coal_dialog", "C级"))
        self.comboBox_8.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_8.setItemText(1, _translate("base_coal_dialog", "特高"))
        self.comboBox_8.setItemText(2, _translate("base_coal_dialog", "高"))
        self.comboBox_8.setItemText(3, _translate("base_coal_dialog", "中"))
        self.comboBox_8.setItemText(4, _translate("base_coal_dialog", "低"))
        self.comboBox_8.setItemText(5, _translate("base_coal_dialog", "特低"))
        self.label.setText(_translate("base_coal_dialog", "基础煤种筛选条件"))
        self.label_9.setText(_translate("base_coal_dialog", "硫分"))
        self.comboBox_6.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_6.setItemText(1, _translate("base_coal_dialog", "硬煤"))
        self.comboBox_6.setItemText(2, _translate("base_coal_dialog", "半硬优"))
        self.comboBox_6.setItemText(3, _translate("base_coal_dialog", "半硬"))
        self.comboBox_6.setItemText(4, _translate("base_coal_dialog", "半软"))
        self.comboBox_6.setItemText(5, _translate("base_coal_dialog", "软煤"))
        self.comboBox_2.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_2.setItemText(1, _translate("base_coal_dialog", "焦煤"))
        self.comboBox_2.setItemText(2, _translate("base_coal_dialog", "肥煤"))
        self.comboBox_2.setItemText(3, _translate("base_coal_dialog", "气煤"))
        self.comboBox_2.setItemText(4, _translate("base_coal_dialog", "1/3焦煤"))
        self.comboBox_2.setItemText(5, _translate("base_coal_dialog", "瘦煤"))
        self.label_4.setText(_translate("base_coal_dialog", "数据年份"))
        self.label_6.setText(_translate("base_coal_dialog", "煤质分级"))
        self.comboBox_4.setItemText(0, _translate("base_coal_dialog", "所有"))
        self.comboBox_4.setItemText(1, _translate("base_coal_dialog", "特等"))
        self.comboBox_4.setItemText(2, _translate("base_coal_dialog", "优质"))
        self.comboBox_4.setItemText(3, _translate("base_coal_dialog", "中等"))
        self.comboBox_4.setItemText(4, _translate("base_coal_dialog", "一般"))
        self.result_table.setSortingEnabled(True)

